name: duwin
description: An exclusive e-library app for Teacher Su Center Ltd..

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  graphql_flutter: ^5.1.0
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.9
  json_annotation: ^4.4.0
  auto_size_text: ^3.0.0
  aad_oauth: ^0.3.0
  flutter_secure_storage: ^4.2.1
  http: ^0.13.4
  jwt_decode: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.8
  json_serializable: ^6.1.5

flutter:

  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: FuturaBold
      fonts:
        - asset: fonts/Futura.otf
          weight: 700

